Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from graspologic.cluster import AutoGMMCluster

labels = AutoGMMCluster(max_components=10, random_state=0).fit_predict(embedding)
fig = pairplot(embedding, labels=labels, title="(B) AutoGMM Clustering, automatic selection", 
                  legend_name="Predicted Clusters", palette=sns.color_palette("colorblind", 10))

fig.tight_layout()

fname = "pairplot_impute1"
if mode != "png":
    fig.savefig(f"Figures/{mode:s}/{fname:s}.{mode:s}")

fig.savefig(f"Figures/png/{fname:s}.png")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[10], line 5[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mgraspologic[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcluster[39;00m [38;5;28;01mimport[39;00m AutoGMMCluster
[1;32m      3[0m labels [38;5;241m=[39m AutoGMMCluster(max_components[38;5;241m=[39m[38;5;241m10[39m, random_state[38;5;241m=[39m[38;5;241m0[39m)[38;5;241m.[39mfit_predict(embedding)
[1;32m      4[0m fig [38;5;241m=[39m pairplot(embedding, labels[38;5;241m=[39mlabels, title[38;5;241m=[39m[38;5;124m"[39m[38;5;124m(B) AutoGMM Clustering, automatic selection[39m[38;5;124m"[39m, 
[0;32m----> 5[0m                   legend_name[38;5;241m=[39m[38;5;124m"[39m[38;5;124mPredicted Clusters[39m[38;5;124m"[39m, palette[38;5;241m=[39m[43msns[49m[38;5;241m.[39mcolor_palette([38;5;124m"[39m[38;5;124mcolorblind[39m[38;5;124m"[39m, [38;5;241m10[39m))
[1;32m      7[0m fig[38;5;241m.[39mtight_layout()
[1;32m      9[0m fname [38;5;241m=[39m [38;5;124m"[39m[38;5;124mpairplot_impute1[39m[38;5;124m"[39m

[0;31mNameError[0m: name 'sns' is not defined

