Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from graphbook_code import plot_vector
import numpy as np

n = 100  # number of students

fig, axs = plt.subplots(1, 2, figsize=(10, 5), gridspec_kw={"width_ratios": [.3, 1]})
# z is a column vector of 50 1s followed by 50 2s
# this vector gives the school each of the 100 students are from
z = np.repeat([1, 2], repeats=n//2)
plot_vector(z.astype(int), title="(A) $\\vec z$, Node Assignment Vector",
            legend_title="School", 
            ticks=[0.5, 49.5, 99.5], ticklabels=[1, 50, 100],
            ticktitle="Student", ax=axs[0])

from graphbook_code import heatmap

K = 2  # community count
# construct the block matrix B as described above
B = np.array([[0.6, 0.1], 
              [0.1, 0.4]])

heatmap(B, xticklabels=[1, 2], yticklabels=[1,2], vmin=0, 
             vmax=1, annot=True, xtitle="School",
             ytitle="School", title="(B) Block Matrix $B$", legend_title="Block probability", ax=axs[1])

fig.tight_layout()

os.makedirs("Figures", exist_ok=True)
fname = "sbm"
if mode != "png":
    os.makedirs(f"Figures/{mode:s}", exist_ok=True)
    fig.savefig(f"Figures/{mode:s}/{fname:s}.{mode:s}")

os.makedirs("Figures/png", exist_ok=True)
fig.savefig(f"Figures/png/{fname:s}.png")
------------------

----- stderr -----
/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 28[0m
[1;32m     22[0m heatmap(B, xticklabels[38;5;241m=[39m[[38;5;241m1[39m, [38;5;241m2[39m], yticklabels[38;5;241m=[39m[[38;5;241m1[39m,[38;5;241m2[39m], vmin[38;5;241m=[39m[38;5;241m0[39m, 
[1;32m     23[0m              vmax[38;5;241m=[39m[38;5;241m1[39m, annot[38;5;241m=[39m[38;5;28;01mTrue[39;00m, xtitle[38;5;241m=[39m[38;5;124m"[39m[38;5;124mSchool[39m[38;5;124m"[39m,
[1;32m     24[0m              ytitle[38;5;241m=[39m[38;5;124m"[39m[38;5;124mSchool[39m[38;5;124m"[39m, title[38;5;241m=[39m[38;5;124m"[39m[38;5;124m(B) Block Matrix $B$[39m[38;5;124m"[39m, legend_title[38;5;241m=[39m[38;5;124m"[39m[38;5;124mBlock probability[39m[38;5;124m"[39m, ax[38;5;241m=[39maxs[[38;5;241m1[39m])
[1;32m     26[0m fig[38;5;241m.[39mtight_layout()
[0;32m---> 28[0m [43mos[49m[38;5;241m.[39mmakedirs([38;5;124m"[39m[38;5;124mFigures[39m[38;5;124m"[39m, exist_ok[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m     29[0m fname [38;5;241m=[39m [38;5;124m"[39m[38;5;124msbm[39m[38;5;124m"[39m
[1;32m     30[0m [38;5;28;01mif[39;00m mode [38;5;241m!=[39m [38;5;124m"[39m[38;5;124mpng[39m[38;5;124m"[39m:

[0;31mNameError[0m: name 'os' is not defined

